const periodicTable = {
    elements: [
      {
        name: "Deiterium",
        symbol: "D",
        protons: 2,
        shells: [1]
      },
      {
        name: "Hydrogen",
        appearance: "colorless gas",
        atomic_mass: 1.008,
        boil: 20.271,
        category: "diatomic nonmetal",
        density: 0.08988,
        discovered_by: "Henry Cavendish",
        melt: 13.99,
        molar_heat: 28.836,
        named_by: "Antoine Lavoisier",
        number: 1,
        period: 1,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Hydrogen",
        spectral_img: "https://en.wikipedia.org/wiki/File:Hydrogen_Spectra.jpg",
        summary: "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
        symbol: "H",
        xpos: 1,
        ypos: 1,
        shells: [
          1
        ],
        electron_configuration: "1s1",
        electron_configuration_semantic: "1s1",
        electron_affinity: 72.769,
        electronegativity_pauling: 2.2,
        ionization_energies: [
          1312
        ],
        cpkhex: "ffffff"
      },
      {
        name: "Helium",
        appearance: "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
        atomic_mass: 4.0026022,
        boil: 4.222,
        category: "noble gas",
        density: 0.1786,
        discovered_by: "Pierre Janssen",
        melt: 0.95,
        molar_heat: null,
        named_by: null,
        number: 2,
        period: 1,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Helium",
        spectral_img: "https://en.wikipedia.org/wiki/File:Helium_spectrum.jpg",
        summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements.",
        symbol: "He",
        xpos: 18,
        ypos: 1,
        shells: [
          2
        ],
        electron_configuration: "1s2",
        electron_configuration_semantic: "1s2",
        electron_affinity: -48,
        electronegativity_pauling: null,
        ionization_energies: [
          2372.3,
          5250.5
        ],
        cpkhex: "d9ffff"
      },
      {
        name: "Lithium",
        appearance: "silvery-white",
        atomic_mass: 6.94,
        boil: 1603,
        category: "alkali metal",
        density: 0.534,
        discovered_by: "Johan August Arfwedson",
        melt: 453.65,
        molar_heat: 24.86,
        named_by: null,
        number: 3,
        period: 2,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Lithium",
        spectral_img: null,
        summary: "Lithium (from Greek:λίθος lithos, \"stone\") is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element.",
        symbol: "Li",
        xpos: 1,
        ypos: 2,
        shells: [
          2,
          1
        ],
        electron_configuration: "1s2 2s1",
        electron_configuration_semantic: "[He] 2s1",
        electron_affinity: 59.6326,
        electronegativity_pauling: 0.98,
        ionization_energies: [
          520.2,
          7298.1,
          11815
        ],
        cpkhex: "cc80ff"
      },
      {
        name: "Beryllium",
        appearance: "white-gray metallic",
        atomic_mass: 9.01218315,
        boil: 2742,
        category: "alkaline earth metal",
        density: 1.85,
        discovered_by: "Louis Nicolas Vauquelin",
        melt: 1560,
        molar_heat: 16.443,
        named_by: null,
        number: 4,
        period: 2,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Beryllium",
        spectral_img: null,
        summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is created through stellar nucleosynthesis and is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals.",
        symbol: "Be",
        xpos: 2,
        ypos: 2,
        shells: [
          2,
          2
        ],
        electron_configuration: "1s2 2s2",
        electron_configuration_semantic: "[He] 2s2",
        electron_affinity: -48,
        electronegativity_pauling: 1.57,
        ionization_energies: [
          899.5,
          1757.1,
          14848.7,
          21006.6
        ],
        cpkhex: "c2ff00"
      },
      {
        name: "Boron",
        appearance: "black-brown",
        atomic_mass: 10.81,
        boil: 4200,
        category: "metalloid",
        density: 2.08,
        discovered_by: "Joseph Louis Gay-Lussac",
        melt: 2349,
        molar_heat: 11.087,
        named_by: null,
        number: 5,
        period: 2,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Boron",
        spectral_img: null,
        summary: "Boron is a metalloid chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in both the Solar system and the Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals.",
        symbol: "B",
        xpos: 13,
        ypos: 2,
        shells: [
          2,
          3
        ],
        electron_configuration: "1s2 2s2 2p1",
        electron_configuration_semantic: "[He] 2s2 2p1",
        electron_affinity: 26.989,
        electronegativity_pauling: 2.04,
        ionization_energies: [
          800.6,
          2427.1,
          3659.7,
          25025.8,
          32826.7
        ],
        cpkhex: "ffb5b5"
      },
      {
        name: "Carbon",
        appearance: null,
        atomic_mass: 12.011,
        boil: null,
        category: "polyatomic nonmetal",
        density: 1.821,
        discovered_by: "Ancient Egypt",
        melt: null,
        molar_heat: 8.517,
        named_by: null,
        number: 6,
        period: 2,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Carbon",
        spectral_img: "https://en.wikipedia.org/wiki/File:Carbon_Spectra.jpg",
        summary: "Carbon (from Latin:carbo \"coal\") is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first (row 2) of six elements in column (group) 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
        symbol: "C",
        xpos: 14,
        ypos: 2,
        shells: [
          2,
          4
        ],
        electron_configuration: "1s2 2s2 2p2",
        electron_configuration_semantic: "[He] 2s2 2p2",
        electron_affinity: 121.7763,
        electronegativity_pauling: 2.55,
        ionization_energies: [
          1086.5,
          2352.6,
          4620.5,
          6222.7,
          37831,
          47277
        ],
        cpkhex: "909090"
      },
      {
        name: "Nitrogen",
        appearance: "colorless gas, liquid or solid",
        atomic_mass: 14.007,
        boil: 77.355,
        category: "diatomic nonmetal",
        density: 1.251,
        discovered_by: "Daniel Rutherford",
        melt: 63.15,
        molar_heat: null,
        named_by: "Jean-Antoine Chaptal",
        number: 7,
        period: 2,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Nitrogen",
        spectral_img: "https://en.wikipedia.org/wiki/File:Nitrogen_Spectra.jpg",
        summary: "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest pnictogen and at room temperature, it is a transparent, odorless diatomic gas. Nitrogen is a common element in the universe, estimated at about seventh in total abundance in the Milky Way and the Solar System.",
        symbol: "N",
        xpos: 15,
        ypos: 2,
        shells: [
          2,
          5
        ],
        electron_configuration: "1s2 2s2 2p3",
        electron_configuration_semantic: "[He] 2s2 2p3",
        electron_affinity: -6.8,
        electronegativity_pauling: 3.04,
        ionization_energies: [
          1402.3,
          2856,
          4578.1,
          7475,
          9444.9,
          53266.6,
          64360
        ],
        cpkhex: "3050f8"
      },
      {
        name: "Oxygen",
        appearance: null,
        atomic_mass: 15.999,
        boil: 90.188,
        category: "diatomic nonmetal",
        density: 1.429,
        discovered_by: "Carl Wilhelm Scheele",
        melt: 54.36,
        molar_heat: null,
        named_by: "Antoine Lavoisier",
        number: 8,
        period: 2,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Oxygen",
        spectral_img: "https://en.wikipedia.org/wiki/File:Oxygen_spectre.jpg",
        summary: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.",
        symbol: "O",
        xpos: 16,
        ypos: 2,
        shells: [
          2,
          6
        ],
        electron_configuration: "1s2 2s2 2p4",
        electron_configuration_semantic: "[He] 2s2 2p4",
        electron_affinity: 140.976,
        electronegativity_pauling: 3.44,
        ionization_energies: [
          1313.9,
          3388.3,
          5300.5,
          7469.2,
          10989.5,
          13326.5,
          71330,
          84078
        ],
        cpkhex: "ff0d0d"
      },
      {
        name: "Fluorine",
        appearance: null,
        atomic_mass: 18.9984031636,
        boil: 85.03,
        category: "diatomic nonmetal",
        density: 1.696,
        discovered_by: "André-Marie Ampère",
        melt: 53.48,
        molar_heat: null,
        named_by: "Humphry Davy",
        number: 9,
        period: 2,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Fluorine",
        spectral_img: null,
        summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive:almost all other elements, including some noble gases, form compounds with fluorine.",
        symbol: "F",
        xpos: 17,
        ypos: 2,
        shells: [
          2,
          7
        ],
        electron_configuration: "1s2 2s2 2p5",
        electron_configuration_semantic: "[He] 2s2 2p5",
        electron_affinity: 328.1649,
        electronegativity_pauling: 3.98,
        ionization_energies: [
          1681,
          3374.2,
          6050.4,
          8407.7,
          11022.7,
          15164.1,
          17868,
          92038.1,
          106434.3
        ],
        cpkhex: "90e050"
      },
      {
        name: "Neon",
        appearance: "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
        atomic_mass: 20.17976,
        boil: 27.104,
        category: "noble gas",
        density: 0.9002,
        discovered_by: "Morris Travers",
        melt: 24.56,
        molar_heat: null,
        named_by: null,
        number: 10,
        period: 2,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Neon",
        spectral_img: "https://en.wikipedia.org/wiki/File:Neon_spectra.jpg",
        summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 (noble gases) of the periodic table. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
        symbol: "Ne",
        xpos: 18,
        ypos: 2,
        shells: [
          2,
          8
        ],
        electron_configuration: "1s2 2s2 2p6",
        electron_configuration_semantic: "[He] 2s2 2p6",
        electron_affinity: -116,
        electronegativity_pauling: null,
        ionization_energies: [
          2080.7,
          3952.3,
          6122,
          9371,
          12177,
          15238,
          19999,
          23069.5,
          115379.5,
          131432
        ],
        cpkhex: "b3e3f5"
      },
      {
        name: "Sodium",
        appearance: "silvery white metallic",
        atomic_mass: 22.989769282,
        boil: 1156.09,
        category: "alkali metal",
        density: 0.968,
        discovered_by: "Humphry Davy",
        melt: 370.944,
        molar_heat: 28.23,
        named_by: null,
        number: 11,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Sodium",
        spectral_img: "https://en.wikipedia.org/wiki/File:Sodium_Spectra.jpg",
        summary: "Sodium /ˈsoʊdiəm/ is a chemical element with symbol Na (from Ancient Greek Νάτριο) and atomic number 11. It is a soft, silver-white, highly reactive metal. In the Periodic table it is in column 1 (alkali metals), and shares with the other six elements in that column that it has a single electron in its outer shell, which it readily donates, creating a positively charged atom - a cation.",
        symbol: "Na",
        xpos: 1,
        ypos: 3,
        shells: [
          2,
          8,
          1
        ],
        electron_configuration: "1s2 2s2 2p6 3s1",
        electron_configuration_semantic: "[Ne] 3s1",
        electron_affinity: 52.867,
        electronegativity_pauling: 0.93,
        ionization_energies: [
          495.8,
          4562,
          6910.3,
          9543,
          13354,
          16613,
          20117,
          25496,
          28932,
          141362,
          159076
        ],
        cpkhex: "ab5cf2"
      },
      {
        name: "Magnesium",
        appearance: "shiny grey solid",
        atomic_mass: 24.305,
        boil: 1363,
        category: "alkaline earth metal",
        density: 1.738,
        discovered_by: "Joseph Black",
        melt: 923,
        molar_heat: 24.869,
        named_by: null,
        number: 12,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Magnesium",
        spectral_img: "https://en.wikipedia.org/wiki/File:Magnesium_Spectra.jpg",
        summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals) of the periodic table:they each have the same electron configuration in their outer electron shell producing a similar crystal structure. Magnesium is the ninth most abundant element in the universe.",
        symbol: "Mg",
        xpos: 2,
        ypos: 3,
        shells: [
          2,
          8,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2",
        electron_configuration_semantic: "[Ne] 3s2",
        electron_affinity: -40,
        electronegativity_pauling: 1.31,
        ionization_energies: [
          737.7,
          1450.7,
          7732.7,
          10542.5,
          13630,
          18020,
          21711,
          25661,
          31653,
          35458,
          169988,
          189368
        ],
        cpkhex: "8aff00"
      },
      {
        name: "Aluminium",
        appearance: "silvery gray metallic",
        atomic_mass: 26.98153857,
        boil: 2743,
        category: "post-transition metal",
        density: 2.7,
        discovered_by: null,
        melt: 933.47,
        molar_heat: 24.2,
        named_by: "Humphry Davy",
        number: 13,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Aluminium",
        spectral_img: null,
        summary: "Aluminium (or aluminum; see different endings) is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal. Aluminium is the third most abundant element (after oxygen and silicon), and the most abundant metal, in the Earth's crust.",
        symbol: "Al",
        xpos: 13,
        ypos: 3,
        shells: [
          2,
          8,
          3
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p1",
        electron_configuration_semantic: "[Ne] 3s2 3p1",
        electron_affinity: 41.762,
        electronegativity_pauling: 1.61,
        ionization_energies: [
          577.5,
          1816.7,
          2744.8,
          11577,
          14842,
          18379,
          23326,
          27465,
          31853,
          38473,
          42647,
          201266,
          222316
        ],
        cpkhex: "bfa6a6"
      },
      {
        name: "Silicon",
        appearance: "crystalline, reflective with bluish-tinged faces",
        atomic_mass: 28.085,
        boil: 3538,
        category: "metalloid",
        density: 2.329,
        discovered_by: "Jöns Jacob Berzelius",
        melt: 1687,
        molar_heat: 19.789,
        named_by: "Thomas Thomson (chemist)",
        number: 14,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Silicon",
        spectral_img: "https://en.wikipedia.org/wiki/File:Silicon_Spectra.jpg",
        summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a tetravalent metalloid, more reactive than germanium, the metalloid directly below it in the table. Controversy about silicon's character dates to its discovery.",
        symbol: "Si",
        xpos: 14,
        ypos: 3,
        shells: [
          2,
          8,
          4
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p2",
        electron_configuration_semantic: "[Ne] 3s2 3p2",
        electron_affinity: 134.0684,
        electronegativity_pauling: 1.9,
        ionization_energies: [
          786.5,
          1577.1,
          3231.6,
          4355.5,
          16091,
          19805,
          23780,
          29287,
          33878,
          38726,
          45962,
          50502,
          235196,
          257923
        ],
        cpkhex: "f0c8a0"
      },
      {
        name: "Phosphorus",
        appearance: "colourless, waxy white, yellow, scarlet, red, violet, black",
        atomic_mass: 30.9737619985,
        boil: null,
        category: "polyatomic nonmetal",
        density: 1.823,
        discovered_by: "Hennig Brand",
        melt: null,
        molar_heat: 23.824,
        named_by: null,
        number: 15,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Phosphorus",
        spectral_img: null,
        summary: "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but due to its high reactivity, phosphorus is never found as a free element on Earth. Instead phosphorus-containing minerals are almost always present in their maximally oxidised state, as inorganic phosphate rocks.",
        symbol: "P",
        xpos: 15,
        ypos: 3,
        shells: [
          2,
          8,
          5
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p3",
        electron_configuration_semantic: "[Ne] 3s2 3p3",
        electron_affinity: 72.037,
        electronegativity_pauling: 2.19,
        ionization_energies: [
          1011.8,
          1907,
          2914.1,
          4963.6,
          6273.9,
          21267,
          25431,
          29872,
          35905,
          40950,
          46261,
          54110,
          59024,
          271791,
          296195
        ],
        cpkhex: "ff8000"
      },
      {
        name: "Sulfur",
        appearance: "lemon yellow sintered microcrystals",
        atomic_mass: 32.06,
        boil: 717.8,
        category: "polyatomic nonmetal",
        density: 2.07,
        discovered_by: "Ancient china",
        melt: 388.36,
        molar_heat: 22.75,
        named_by: null,
        number: 16,
        period: 3,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Sulfur",
        spectral_img: "https://en.wikipedia.org/wiki/File:Sulfur_Spectrum.jpg",
        summary: "Sulfur or sulphur (see spelling differences) is a chemical element with symbol S and atomic number 16. It is an abundant, multivalent non-metal. Under normal conditions, sulfur atoms form cyclic octatomic molecules with chemical formula S8.",
        symbol: "S",
        xpos: 16,
        ypos: 3,
        shells: [
          2,
          8,
          6
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p4",
        electron_configuration_semantic: "[Ne] 3s2 3p4",
        electron_affinity: 200.4101,
        electronegativity_pauling: 2.58,
        ionization_energies: [
          999.6,
          2252,
          3357,
          4556,
          7004.3,
          8495.8,
          27107,
          31719,
          36621,
          43177,
          48710,
          54460,
          62930,
          68216,
          311048,
          337138
        ],
        cpkhex: "ffff30"
      },
      {
        name: "Chlorine",
        appearance: "pale yellow-green gas",
        atomic_mass: 35.45,
        boil: 239.11,
        category: "diatomic nonmetal",
        density: 3.2,
        discovered_by: "Carl Wilhelm Scheele",
        melt: 171.6,
        molar_heat: null,
        named_by: null,
        number: 17,
        period: 3,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Chlorine",
        spectral_img: "https://en.wikipedia.org/wiki/File:Chlorine_spectrum_visible.png",
        summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. It also has a relative atomic mass of 35.5. Chlorine is in the halogen group (17) and is the second lightest halogen following fluorine.",
        symbol: "Cl",
        xpos: 17,
        ypos: 3,
        shells: [
          2,
          8,
          7
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p5",
        electron_configuration_semantic: "[Ne] 3s2 3p5",
        electron_affinity: 348.575,
        electronegativity_pauling: 3.16,
        ionization_energies: [
          1251.2,
          2298,
          3822,
          5158.6,
          6542,
          9362,
          11018,
          33604,
          38600,
          43961,
          51068,
          57119,
          63363,
          72341,
          78095,
          352994,
          380760
        ],
        cpkhex: "1ff01f"
      },
      {
        name: "Argon",
        appearance: "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
        atomic_mass: 39.9481,
        boil: 87.302,
        category: "noble gas",
        density: 1.784,
        discovered_by: "Lord Rayleigh",
        melt: 83.81,
        molar_heat: null,
        named_by: null,
        number: 18,
        period: 3,
        phase: "Gas",
        source: "https://en.wikipedia.org/wiki/Argon",
        spectral_img: "https://en.wikipedia.org/wiki/File:Argon_Spectrum.png",
        summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth's atmosphere, at 0.934% (9,340 ppmv), making it over twice as abundant as the next most common atmospheric gas, water vapor (which averages about 4000 ppmv, but varies greatly), and 23 times as abundant as the next most common non-condensing atmospheric gas, carbon dioxide (400 ppmv), and more than 500 times as abundant as the next most common noble gas, neon (18 ppmv).",
        symbol: "Ar",
        xpos: 18,
        ypos: 3,
        shells: [
          2,
          8,
          8
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6",
        electron_configuration_semantic: "[Ne] 3s2 3p6",
        electron_affinity: -96,
        electronegativity_pauling: null,
        ionization_energies: [
          1520.6,
          2665.8,
          3931,
          5771,
          7238,
          8781,
          11995,
          13842,
          40760,
          46186,
          52002,
          59653,
          66199,
          72918,
          82473,
          88576,
          397605,
          427066
        ],
        cpkhex: "80d1e3"
      },
      {
        name: "Potassium",
        appearance: "silvery gray",
        atomic_mass: 39.09831,
        boil: 1032,
        category: "alkali metal",
        density: 0.862,
        discovered_by: "Humphry Davy",
        melt: 336.7,
        molar_heat: 29.6,
        named_by: null,
        number: 19,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Potassium",
        spectral_img: "https://en.wikipedia.org/wiki/File:Potassium_Spectrum.jpg",
        summary: "Potassium is a chemical element with symbol K (derived from Neo-Latin, kalium) and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name is derived. In the Periodic table, potassium is one of seven elements in column (group) 1 (alkali metals):they all have a single valence electron in their outer electron shell, which they readily give up to create an atom with a positive charge - a cation, and combine with anions to form salts.",
        symbol: "K",
        xpos: 1,
        ypos: 4,
        shells: [
          2,
          8,
          8,
          1
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s1",
        electron_configuration_semantic: "[Ar] 4s1",
        electron_affinity: 48.383,
        electronegativity_pauling: 0.82,
        ionization_energies: [
          418.8,
          3052,
          4420,
          5877,
          7975,
          9590,
          11343,
          14944,
          16963.7,
          48610,
          54490,
          60730,
          68950,
          75900,
          83080,
          93400,
          99710,
          444880,
          476063
        ],
        cpkhex: "8f40d4"
      },
      {
        name: "Calcium",
        appearance: null,
        atomic_mass: 40.0784,
        boil: 1757,
        category: "alkaline earth metal",
        density: 1.55,
        discovered_by: "Humphry Davy",
        melt: 1115,
        molar_heat: 25.929,
        named_by: null,
        number: 20,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Calcium",
        spectral_img: "https://en.wikipedia.org/wiki/File:Calcium_Spectrum.png",
        summary: "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust. The ion Ca2+ is also the fifth-most-abundant dissolved ion in seawater by both molarity and mass, after sodium, chloride, magnesium, and sulfate.",
        symbol: "Ca",
        xpos: 2,
        ypos: 4,
        shells: [
          2,
          8,
          8,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2",
        electron_configuration_semantic: "[Ar] 4s2",
        electron_affinity: 2.37,
        electronegativity_pauling: 1,
        ionization_energies: [
          589.8,
          1145.4,
          4912.4,
          6491,
          8153,
          10496,
          12270,
          14206,
          18191,
          20385,
          57110,
          63410,
          70110,
          78890,
          86310,
          94000,
          104900,
          111711,
          494850,
          527762
        ],
        cpkhex: "3dff00"
      },
      {
        name: "Scandium",
        appearance: "silvery white",
        atomic_mass: 44.9559085,
        boil: 3109,
        category: "transition metal",
        density: 2.985,
        discovered_by: "Lars Fredrik Nilson",
        melt: 1814,
        molar_heat: 25.52,
        named_by: null,
        number: 21,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Scandium",
        spectral_img: null,
        summary: "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element, together with yttrium and the lanthanoids. It was discovered in 1879 by spectral analysis of the minerals euxenite and gadolinite from Scandinavia.",
        symbol: "Sc",
        xpos: 3,
        ypos: 4,
        shells: [
          2,
          8,
          9,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2 3d1",
        electron_configuration_semantic: "[Ar] 3d1 4s2",
        electron_affinity: 18,
        electronegativity_pauling: 1.36,
        ionization_energies: [
          633.1,
          1235,
          2388.6,
          7090.6,
          8843,
          10679,
          13310,
          15250,
          17370,
          21726,
          24102,
          66320,
          73010,
          80160,
          89490,
          97400,
          105600,
          117000,
          124270,
          547530,
          582163
        ],
        cpkhex: "e6e6e6"
      },
      {
        name: "Titanium",
        appearance: "silvery grey-white metallic",
        atomic_mass: 47.8671,
        boil: 3560,
        category: "transition metal",
        density: 4.506,
        discovered_by: "William Gregor",
        melt: 1941,
        molar_heat: 25.06,
        named_by: "Martin Heinrich Klaproth",
        number: 22,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Titanium",
        spectral_img: null,
        summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density and high strength. It is highly resistant to corrosion in sea water, aqua regia and chlorine.",
        symbol: "Ti",
        xpos: 4,
        ypos: 4,
        shells: [
          2,
          8,
          10,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2 3d2",
        electron_configuration_semantic: "[Ar] 3d2 4s2",
        electron_affinity: 7.289,
        electronegativity_pauling: 1.54,
        ionization_energies: [
          658.8,
          1309.8,
          2652.5,
          4174.6,
          9581,
          11533,
          13590,
          16440,
          18530,
          20833,
          25575,
          28125,
          76015,
          83280,
          90880,
          100700,
          109100,
          117800,
          129900,
          137530,
          602930,
          639294
        ],
        cpkhex: "bfc2c7"
      },
      {
        name: "Vanadium",
        appearance: "blue-silver-grey metal",
        atomic_mass: 50.94151,
        boil: 3680,
        category: "transition metal",
        density: 6,
        discovered_by: "Andrés Manuel del Río",
        melt: 2183,
        molar_heat: 24.89,
        named_by: "Isotopes of vanadium",
        number: 23,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Vanadium",
        spectral_img: null,
        summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile and malleable transition metal. The element is found only in chemically combined form in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation.",
        symbol: "V",
        xpos: 5,
        ypos: 4,
        shells: [
          2,
          8,
          11,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2 3d3",
        electron_configuration_semantic: "[Ar] 3d3 4s2",
        electron_affinity: 50.911,
        electronegativity_pauling: 1.63,
        ionization_energies: [
          650.9,
          1414,
          2830,
          4507,
          6298.7,
          12363,
          14530,
          16730,
          19860,
          22240,
          24670,
          29730,
          32446,
          86450,
          94170,
          102300,
          112700,
          121600,
          130700,
          143400,
          151440,
          661050,
          699144
        ],
        cpkhex: "a6a6ab"
      },
      {
        name: "Chromium",
        appearance: "silvery metallic",
        atomic_mass: 51.99616,
        boil: 2944,
        category: "transition metal",
        density: 7.19,
        discovered_by: "Louis Nicolas Vauquelin",
        melt: 2180,
        molar_heat: 23.35,
        named_by: null,
        number: 24,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Chromium",
        spectral_img: null,
        summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-gray, lustrous, hard and brittle metal which takes a high polish, resists tarnishing, and has a high melting point.",
        symbol: "Cr",
        xpos: 6,
        ypos: 4,
        shells: [
          2,
          8,
          13,
          1
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s1 3d5",
        electron_configuration_semantic: "[Ar] 3d5 4s1",
        electron_affinity: 65.21,
        electronegativity_pauling: 1.66,
        ionization_energies: [
          652.9,
          1590.6,
          2987,
          4743,
          6702,
          8744.9,
          15455,
          17820,
          20190,
          23580,
          26130,
          28750,
          34230,
          37066,
          97510,
          105800,
          114300,
          125300,
          134700,
          144300,
          157700,
          166090,
          721870,
          761733
        ],
        cpkhex: "8a99c7"
      },
      {
        name: "Manganese",
        appearance: "silvery metallic",
        atomic_mass: 54.9380443,
        boil: 2334,
        category: "transition metal",
        density: 7.21,
        discovered_by: "Torbern Olof Bergman",
        melt: 1519,
        molar_heat: 26.32,
        named_by: null,
        number: 25,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Manganese",
        spectral_img: null,
        summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in combination with iron, and in many minerals. Manganese is a metal with important industrial metal alloy uses, particularly in stainless steels.",
        symbol: "Mn",
        xpos: 7,
        ypos: 4,
        shells: [
          2,
          8,
          13,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2 3d5",
        electron_configuration_semantic: "[Ar] 3d5 4s2",
        electron_affinity: -50,
        electronegativity_pauling: 1.55,
        ionization_energies: [
          717.3,
          1509,
          3248,
          4940,
          6990,
          9220,
          11500,
          18770,
          21400,
          23960,
          27590,
          30330,
          33150,
          38880,
          41987,
          109480,
          118100,
          127100,
          138600,
          148500,
          158600,
          172500,
          181380,
          785450,
          827067
        ],
        cpkhex: "9c7ac7"
      },
      {
        name: "Iron",
        appearance: "lustrous metallic with a grayish tinge",
        atomic_mass: 55.8452,
        boil: 3134,
        category: "transition metal",
        density: 7.874,
        discovered_by: "5000 BC",
        melt: 1811,
        molar_heat: 25.1,
        named_by: null,
        number: 26,
        period: 4,
        phase: "Solid",
        source: "https://en.wikipedia.org/wiki/Iron",
        spectral_img: "https://en.wikipedia.org/wiki/File:Iron_Spectrum.jpg",
        summary: "Iron is a chemical element with symbol Fe (from Latin:ferrum) and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core.",
        symbol: "Fe",
        xpos: 8,
        ypos: 4,
        shells: [
          2,
          8,
          14,
          2
        ],
        electron_configuration: "1s2 2s2 2p6 3s2 3p6 4s2 3d6",
        electron_configuration_semantic: "[Ar] 3d6 4s2",
        electron_affinity: 14.785,
        electronegativity_pauling: 1.83,
        ionization_energies: [
          762.5,
          1561.9,
          2957,
          5290,
          7240,
          9560,
          12060,
          14580,
          22540,
          25290,
          28000,
          31920,
          34830,
          37840,
          44100,
          47206,
          122200,
          131000,
          140500,
          152600,
          163000,
          173600,
          188100,
          195200,
          851800,
          895161
        ],
        cpkhex: "e06633"
      }
    ]
  }